services:
  - type: web
    name: nasa-kosmos-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: NASA_API_KEY
        value: DEMO_KEY
      - key: REQUIRED_CHANNELS
        sync: false
      - key: POST_INTERVAL_MINUTES
        value: "5"
      - key: POSTS_PER_BATCH
        value: "10"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
